language: c#
solution: GDPAssessment.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore GDPAssessment.sln
after_script:
  - nunit-console GDPAssessmentTest/bin/Release/GDPAssessmentTest.dll